const gameArray = [
  'Batman.png',
  'bed.png',
  'book.ico',
  'cookies.ico',
  'dog.ico',
  'eye.ico',
  'fish.ico',
  'horse.png',
  'htgawm.png',
  'playstation.png',
  'poi.ico',
  'sneakers.ico',
  'spiderman.png',
  'spongebob.png',
  'superman.png',
  'jug.ico',
  'ironman.ico',
  'ferrari.png',
  'Naruto.ico',
  'mario.ico',
  'brain.ico',
  'black-panther.png',
  'angry_bird.ico',
  'basketball.ico',
  'knife.ico',
  'tv.ico',
  'nigeria.png',
  'guitar.png',
  'lion.png',
  'smile.ico',
  'piano.png',
  'duck.png',
  'football.ico',
  'church.ico',
];

export default gameArray;
